language: node_js

node_js:
  - "8"

before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod

deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: $FIREBASE_TOKEN
  only:
    - master
    - travis
